const genres = [
  "Scifi",
  "Fantasy",
  "Thriller",
  "Action",
  "Adventure",
  "Dystopia",
  "Mystery",
  "Horror",
  "Historical fiction",
  "Romance",
  "Women’s fiction",
  "LGBTQ+",
  "Magical Realism",
  "Graphic Novel",
  "Short story",
  "Young adult",
  "New adult",
  "Childrens",
  "Memoir",
  "Autobiograph",
  "Food and Drink",
  "Art",
  "Self help",
  "History",
  "Travel",
  "True crime",
  "Humor",
  "Essays",
  "Guide / How-to",
  "Religion and Spirituality",
  "Social Sciences",
  "Parenting",
  "Science and Technology",
];
